### post to create new patient in database
POST http://localhost:4000/patients/createPatient
Content-Type: application/json

{
  "name": "sourav",
  "address": "house 24, pali, faridabad, haryana",
  "email": "souravfagna14@gmail.com",
  "dateOfBirth": "2003-09-03"

}

###
